title: Scott B. Weingart
description: Historian of knowledge, professional circus performer, amateur father, and hopeless adventurer. Research affiliate at the University of Edinburgh's Centre for Data, Culture & Society.
#url: https://scottweingart.net
