title: Scott B. Weingart
description: Historian of knowledge, professional circus performer, amateur father, and hopeless adventurer. Resident scholar at Dartmouth College.
#url: https://scottweingart.net
